In [53]:
#packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
import matplotlib.pyplot as plt

In [54]:
df = pd.read_csv("spam.csv")

In [55]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [56]:
print(df)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [57]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [58]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [59]:
train_x,test_x,train_y,test_y = train_test_split(df.Message,df.spam,test_size = 0.25)

In [60]:
cv = CountVectorizer()
tr_count_x = cv.fit_transform(train_x.values)

In [61]:
tr_count_x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [62]:
train_model = MultinomialNB()
train_model.fit(tr_count_x,train_y)

MultinomialNB()

In [63]:
ham_email = ["hello wanna catch up for a game?"]
ham_email_count = cv.transform(ham_email)
train_model.predict(ham_email_count)

array([0])

In [64]:
spam_email = ["reward bonus click"]
spam_email_count = cv.transform(spam_email)
train_model.predict(spam_email_count)

array([1])

In [65]:
test_count_x = cv.transform(test_x)
print("Accuracy:",train_model.score(test_count_x,test_y))

Accuracy: 0.9834888729361091


In [66]:
extract=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

train_ft_x=extract.fit_transform(train_x)
test_ft_y=extract.transform(test_x)
train_y=train_y.astype('int')
test_y=test_y.astype('int')

In [67]:
print(train_ft_x)

  (0, 6709)	0.3656647429961679
  (0, 7030)	0.34299444044204586
  (0, 3478)	0.3349030592302236
  (0, 4397)	0.3349030592302236
  (0, 3104)	0.2606124393945109
  (0, 4067)	0.28374745539502677
  (0, 5711)	0.3528974906923438
  (0, 6817)	0.3656647429961679
  (0, 5319)	0.34299444044204586
  (1, 3257)	0.19348944519654068
  (1, 928)	0.2304289055110911
  (1, 2450)	0.29067457041896355
  (1, 6501)	0.29067457041896355
  (1, 2068)	0.1425041626866504
  (1, 6349)	0.15847186485863163
  (1, 758)	0.277041314697735
  (1, 5236)	0.20575011255143122
  (1, 5683)	0.20316239406863412
  (1, 6045)	0.19961977887398594
  (1, 1256)	0.29067457041896355
  (1, 4915)	0.1646021985360769
  (1, 1773)	0.277041314697735
  (1, 1809)	0.38159621908296826
  (1, 1572)	0.22292598346730788
  (1, 1668)	0.29067457041896355
  :	:
  (4172, 6458)	0.5738532572583176
  (4172, 4290)	0.5389553307220021
  (4172, 2688)	0.43152111271065174
  (4172, 2800)	0.308189430501807
  (4172, 2068)	0.31468777356657723
  (4173, 3524)	0.5605266245938159
  (4

In [68]:
m = LogisticRegression()
m.fit(train_ft_x,train_y)

LogisticRegression()

In [69]:
mail=['Subject: Exclusive Offer Inside - Claim Your Reward Now!']

data_ft = extract.transform(mail)
predict=m.predict(data_ft)
print(predict)

if(predict[0]==1):
    print('Ham mail')
else:
    print('Spam mail')

[0]
Spam mail
